name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot App
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK 21
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      # 3️⃣ Run Unit Tests
      - name: Unit Tests
        working-directory: ./web-app
        run: mvn -B test

      # 4️⃣ Build Application
      - name: Build the application
        working-directory: ./web-app
        run: mvn -B clean package -DskipTests

      # 5️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6️⃣ Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/appcicd:latest
